#require 'cucumber/formatter/unicode' # Remove this line if you don't want Cucumber Unicode support
#require 'cucumber/rails/world'
#require 'cucumber/rails/active_record'
#require 'cucumber/web/tableish'


require 'rubygems'
require 'capybara/cucumber'
require 'capybara'
require 'celerity'
require 'rspec'
require 'net/http'
require 'uri'
require 'time'
require 'htmldiff'
require 'open-uri'
require 'capybara/rspec'
require 'capybara'
require 'websautotest'
#require 'webrat'